name: Buid Backend
on:
  push:
    branches:
      - master
    paths:
      - "**"
      - ".github/workflows/be_carselling.yml"
jobs:
  build-deploy:
    name: Build and Deploy Back-End
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_ACCESS_USER}}
          password: ${{ secrets.DOCKER_ACCESS_KEYS }}

      - name: Build Docker Images
        uses: docker/build-push-action@v2
        with:
          context: ./autohunt-selling-car-backend
          dockerfile: ./be-capstone/Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_ACCESS_USER }}/autohunt-selling-car-backend:latest

      - name: Push to Dockerhub
        uses: docker/build-push-action@v2
        with:
          context: ./be-capstone
          dockerfile: ./be-capstone/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_ACCESS_USER }}/autohunt-selling-car-backendg:latest
          cache-from: type=gha
          cache-to: type=gha, mode=max
