name: Buid Backend
on:
  push:
    branches:
      - master
    paths:
      - "**"
      - ".github/workflows/be_carselling.yml"
jobs:
  build-deploy:
    name: Build and Deploy Back-End
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check sysntax
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_ACCESS_USER}}
          password: ${{ secrets.DOCKER_ACCESS_KEYS }}

      - name: Build Docker Images
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          dockerfile: Dockerfile
          tags: autohunt-selling-car-backend:${{ github.sha }}

      - name: Vulnerability Scan
        uses: lazy-actions/gitrivy@v3
        with:
          images: autohunt-selling-car-backend:${{ github.sha }}
          format: table
        env:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to Dockerhub
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: autohunt-selling-car-backend:latest
          cache-from: type=gha
          cache-to: type=gha, mode=max
