name: Buid Backend
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

    paths:
      - "**"
      - ".github/workflows/be_carselling.yml"
jobs:
  build-deploy:
    name: Build and Deploy Back-End
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check sysntax
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker
        uses: docker/login-action@v3
        with:
          username: "${{ secrets.DOCKER_ACCESS_USER}}"
          password: "${{ secrets.DOCKER_ACCESS_KEYS }}"

      - name: Build Docker Images
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          dockerfile: Dockerfile
          tags: "autohunt-selling-car-backend:${{ github.sha }}"

      - name: Vulnerability Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "autohunt-selling-car-backend:${{ github.sha }}"
          format: table
          exit-code: 1
          severity: CRITICAL

      - name: Push to Dockerhub
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: "${{ secrets.DOCKER_ACCESS_USER }}/autohunt-selling-car-backend:${{ github.sha }}"
          cache-from: type=gha
          cache-to: type=gha, mode=max
